version: '2'

services:
    nginx-web-container:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./php-code:/php-code
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - backend
    php-app-container:
        image: php:fpm
        volumes:
            - ./php-code:/php-code
        networks:
            - backend

networks:
    backend:
        driver: bridge
